---
formatter: markdown table

header-from: main.tf
footer-from: ""

sections:
  hide: []
  show: []

content: |-
  # Terraform Configuration for Elasticsearch Aggregate Thresholds

  This Terraform configuration manages Elasticsearch indices, ingest pipelines, and transforms for the aggregate thresholds system.

  ## Architecture

  For the moment this example imagines monitoring of mysql and kafka.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

output:
  file: README.md
  mode: replace

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
