[tools]
lazydocker = "latest"
ripgrep = "14.1.0"
colima = "latest"
tflint = "latest"
terraform-validator = "latest"
checkov = "latest"
uv = "latest"
terraform = "latest"
node = "latest"
terrascan = "latest"
terraform-docs = "latest"
pre-commit = "latest"
shellcheck = "latest"
go = "latest"
ruff = "latest"
terraform-ls = "latest"
viddy = "latest"
trivy = "latest"
make = "latest"
