global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093
scrape_configs:
 - job_name: ulises-prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: node
   static_configs:
    - targets:
       - node-exporter:9100
 - job_name: snmp_exporter
   static_configs:
    - targets:
       - snmp-exporter:9116
 - job_name: snmp_switches
   static_configs:
    - targets:
      - 127.0.0.1:1611
   metrics_path: /snmp
   params:
    auth: [public_v2]
    module: [if_mib]
   relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9116  # The SNMP exporter's real hostname:port.
